"use client";
import {useMemo,useRef,useState} from "react";
import {ArrowLeft,ArrowRight,Check,Clapperboard,Clock3,Film,GripVertical,Home as HomeIcon,ImagePlus,LayoutGrid,Menu,MoreHorizontal,Play,Plus,RefreshCw,Search,Settings,Sparkles,UploadCloud,UserRound,WandSparkles,X,Zap} from "lucide-react";

type Scene={id:number;tag:string;title:string;text:string;sec:number;cost:number};
const baseScenes:Scene[]=[
 {id:1,tag:"HOOK",title:"O detalhe que muda tudo",text:"Close no produto e reação natural para prender a atenção.",sec:3,cost:8},
 {id:2,tag:"APRESENTAÇÃO",title:"Conheça o produto",text:"A modelo apresenta o produto em um ambiente cotidiano.",sec:4,cost:8},
 {id:3,tag:"DEMONSTRAÇÃO",title:"Produto em uso",text:"Uso real preservando embalagem, cores e proporções.",sec:5,cost:10},
 {id:4,tag:"ENCERRAMENTO",title:"Convite final",text:"Fala natural em português brasileiro e CTA verbal.",sec:3,cost:8}
];
const talents=[["Maya","Creator UGC","maya"],["Luiza","Lifestyle","luiza"],["Nina","Premium","nina"],["Sem modelo","Só o produto","none"]];
const formats=["Vídeo UGC","Review de produto","Unboxing","Demonstração","Lifestyle","Comercial cinematográfico"];

export default function Home(){
 const [view,setView]=useState<"home"|"wizard"|"history">("home"),[step,setStep]=useState(1);
 const [img,setImg]=useState<string|null>(null),[name,setName]=useState(""),[message,setMessage]=useState("");
 const [brief,setBrief]=useState(""),[talent,setTalent]=useState(0),[format,setFormat]=useState(formats[0]),[ratio,setRatio]=useState("9:16"),[duration,setDuration]=useState("15s"),[scenes,setScenes]=useState(baseScenes);
 const input=useRef<HTMLInputElement>(null),total=useMemo(()=>scenes.reduce((a,s)=>a+s.cost,0),[scenes]);
 const start=()=>{setView("wizard");setStep(1);setMessage("")};
 const pick=(file?:File)=>{if(!file)return;if(!/image\/(jpeg|png|webp)/.test(file.type)){setMessage("Envie uma imagem JPG, PNG ou WEBP.");return}if(file.size>10485760){setMessage("A imagem deve ter no máximo 10 MB.");return}setImg(URL.createObjectURL(file));setName(file.name);setMessage("")};
 const next=()=>{if(step===1&&!img){setMessage("Envie ao menos uma foto do produto para continuar.");return}setStep(Math.min(5,step+1));setMessage("")};
 const move=(i:number,d:number)=>{let t=i+d;if(t<0||t>=scenes.length)return;let c=[...scenes];[c[i],c[t]]=[c[t],c[i]];setScenes(c)};
 return <div className="shell">
  <aside><button className="logo" onClick={()=>setView("home")}><b><Sparkles/></b>luna<span>DEV</span></button><nav>
   <button className={view==="home"?"on":""} onClick={()=>setView("home")}><HomeIcon/>Início</button>
   <button className={view==="wizard"?"on":""} onClick={start}><WandSparkles/>Criar campanha</button>
   <button className={view==="history"?"on":""} onClick={()=>setView("history")}><LayoutGrid/>Minhas campanhas</button>
  </nav><div className="sidefoot"><div className="credit"><div><Zap/>Créditos</div><strong>248</strong><small>de 300 disponíveis</small><i><b/></i></div><button><Settings/>Configurações</button><div className="profile"><b>AL</b><span><strong>Alexandre Lima</strong><small>Plano Creator</small></span><MoreHorizontal/></div></div></aside>
  <main><header><button className="logo"><b><Sparkles/></b>luna<span>DEV</span></button><Menu/></header>
   {view==="home"&&<Dashboard start={start} history={()=>setView("history")}/>}
   {view==="history"&&<History start={start}/>}
   {view==="wizard"&&<section className="wizard"><div className="wizhead"><button onClick={()=>step===1?setView("home"):setStep(step-1)}><ArrowLeft/></button><div><span>NOVA CAMPANHA</span><h1>{["Seu produto","Briefing inteligente","Escolha a modelo","Formato do conteúdo","Revise o storyboard"][step-1]}</h1></div><strong>{step}<small>/5</small></strong></div><div className="progress">{[1,2,3,4,5].map(n=><i className={n<=step?"done":""} key={n}/>)}</div>
    {step===1&&<Product img={img} name={name} input={input} pick={pick} remove={()=>{setImg(null);setName("")}}/>}
    {step===2&&<Brief brief={brief} setBrief={setBrief}/>}
    {step===3&&<Talent selected={talent} select={setTalent}/>}
    {step===4&&<Format format={format} setFormat={setFormat} ratio={ratio} setRatio={setRatio} duration={duration} setDuration={setDuration}/>}
    {step===5&&<Storyboard scenes={scenes} setScenes={setScenes} move={move} total={total} talent={talents[talent][0]} format={format} ratio={ratio} duration={duration}/>}
    {message&&<div className="notice">{message}</div>}<div className="actions"><button className="secondary" onClick={()=>step===1?setView("home"):setStep(step-1)}>Voltar</button>{step<5?<button className="primary" onClick={next}>Continuar<ArrowRight/></button>:<button className="primary" onClick={()=>setMessage("Configure as credenciais Gemini no backend para iniciar a geração real. Nenhum crédito foi consumido.")}><Sparkles/>Gerar campanha · {total} créditos</button>}</div>
   </section>}
  </main><nav className="mobileNav"><button onClick={()=>setView("home")}><HomeIcon/>Início</button><button className="new" onClick={start}><Plus/></button><button onClick={()=>setView("history")}><LayoutGrid/>Campanhas</button></nav>
 </div>
}

function Dashboard({start,history}:{start:()=>void;history:()=>void}){return <section className="dashboard"><div className="hello"><div><span>ESTÚDIO CRIATIVO COM IA</span><h1>Olá, Alexandre <b>✦</b></h1><p>Transforme uma foto de produto em uma campanha pronta para publicar.</p></div><button className="primary desk" onClick={start}><Plus/>Criar nova campanha</button></div>
 <button className="hero" onClick={start}><div className="spark"><Sparkles/></div><div><span>COMECE POR AQUI</span><h2>Crie sua próxima campanha</h2><p>Envie o produto. A IA cuida do conceito, modelo, roteiro, cenas e áudio em português.</p><strong>Criar agora <ArrowRight/></strong></div><div className="phone"><i>UGC</i><div><UserRound/><Play/></div><b>9:16 · 15s</b></div></button>
 <div className="sectionTitle"><div><h2>Campanhas recentes</h2><p>Continue de onde parou.</p></div><button onClick={history}>Ver todas <ArrowRight/></button></div><div className="grid"><Campaign title="Glow Serum" meta="Vídeo UGC · 15s" status="Concluído" color="peach"/><Campaign title="Urban Sneakers" meta="Lifestyle · 30s" status="Processando 64%" color="blue"/><Campaign title="Café Origem" meta="Produto premium · 15s" status="Rascunho" color="brown"/></div>
 <div className="tip"><Sparkles/><div><strong>Dica da Luna</strong><p>Comece com um gancho visual forte nos primeiros três segundos.</p></div><button onClick={start}>Criar em 9:16</button></div></section>}
function Campaign({title,meta,status,color}:{title:string;meta:string;status:string;color:string}){return <article className="campaign"><div className={"art "+color}><button><Play/></button><span>{status}</span></div><div><h3>{title}</h3><p>{meta}</p><MoreHorizontal/></div></article>}
function Product({img,name,input,pick,remove}:any){return <Panel><Intro title="Mostre o produto para a Luna" text="Use uma foto nítida, bem iluminada e sem objetos cobrindo a embalagem."/><input ref={input} type="file" hidden accept="image/jpeg,image/png,image/webp" onChange={(e:any)=>pick(e.target.files?.[0])}/>{!img?<button className="drop" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();pick(e.dataTransfer.files[0])}}><b><UploadCloud/></b><strong>Arraste uma foto ou toque para enviar</strong><small>JPG, PNG ou WEBP · máximo 10 MB</small><span>Escolher imagem</span></button>:<div className="uploaded"><img src={img} alt="Produto enviado"/><div><Check/><span><strong>Imagem pronta</strong><small>{name}</small></span><button onClick={remove}><X/></button></div></div>}<p className="privacy"><Check/>Sua imagem será usada apenas para criar esta campanha.</p></Panel>}
function Brief({brief,setBrief}:any){return <Panel><div className="analysis"><b><Sparkles/></b><div><span>ANÁLISE SUGERIDA</span><h3>Produto de beleza · visual clean e luminoso</h3><p>Público sugerido: pessoas de 20 a 40 anos interessadas em autocuidado. Ambiente: bancada clara com luz natural.</p></div><button><RefreshCw/>Nova sugestão</button></div><label className="field"><span>Conte um pouco sobre o produto <em>opcional</em></span><textarea value={brief} onChange={e=>setBrief(e.target.value)} placeholder="Ex.: Sérum vegano, textura leve, ideal para rotina noturna..."/><small>As informações escritas por você sempre têm prioridade.</small></label><div className="fields">{[["Estilo","Natural e sofisticado"],["Público","20–40 anos"],["Conceito","Brilho que nasce do cuidado"],["Ambiente","Banheiro moderno e claro"]].map(x=><label key={x[0]}><span>{x[0]}</span><input defaultValue={x[1]}/></label>)}</div></Panel>}
function Talent({selected,select}:any){return <Panel><Intro title="Quem apresenta sua campanha?" text="Escolha uma personagem consistente para todas as cenas."/><div className="talents">{talents.map((t,i)=><button className={selected===i?"selected":""} onClick={()=>select(i)} key={t[0]}><div className={t[2]}><UserRound/>{selected===i&&<i><Check/></i>}</div><strong>{t[0]}</strong><small>{t[1]}</small></button>)}</div><button className="regen"><RefreshCw/>Gerar novas opções</button><div className="info"><UserRound/><p><strong>Consistência visual ativada</strong>A modelo escolhida será usada como referência em cada cena.</p></div></Panel>}
function Format(p:any){return <Panel><Choice title="Tipo de vídeo"><div className="formats">{formats.map(f=><button className={p.format===f?"selected":""} onClick={()=>p.setFormat(f)} key={f}><Clapperboard/>{f}{p.format===f&&<Check/>}</button>)}</div></Choice><Choice title="Proporção"><div className="ratios">{[["9:16","TikTok, Reels e Shorts"],["1:1","Feed quadrado"],["4:5","Feed Instagram"],["16:9","YouTube e horizontal"]].map(r=><button className={p.ratio===r[0]?"selected":""} onClick={()=>p.setRatio(r[0])} key={r[0]}><i className={"r"+r[0].replace(":","")}/><span><strong>{r[0]}</strong><small>{r[1]}</small></span>{r[0]==="9:16"&&<em>RECOMENDADO</em>}</button>)}</div></Choice><Choice title="Duração"><div className="durations">{["15s","30s","60s"].map(d=><button className={p.duration===d?"selected":""} onClick={()=>p.setDuration(d)} key={d}><Clock3/><strong>{d}</strong><small>{d==="15s"?"Rápido e direto":d==="30s"?"Mais detalhes":"História completa"}</small></button>)}</div></Choice></Panel>}
function Storyboard(p:any){return <div className="story"><div><Intro title="Seu vídeo, cena por cena" text="Revise a direção criativa antes de usar seus créditos." left/>{p.scenes.map((s:Scene,i:number)=><article className="scene" key={s.id}><div><GripVertical/><span>{String(i+1).padStart(2,"0")}</span></div><figure><Film/><small>{s.sec}s</small></figure><section><span>{s.tag}</span><h3>{s.title}</h3><p>{s.text}</p></section><footer><small>{s.cost} créditos</small><button onClick={()=>p.move(i,-1)}>↑</button><button onClick={()=>p.move(i,1)}>↓</button><button onClick={()=>p.setScenes(p.scenes.filter((x:Scene)=>x.id!==s.id))}><X/></button></footer></article>)}<button className="add" onClick={()=>p.setScenes([...p.scenes,{id:Date.now(),tag:"NOVA CENA",title:"Cena adicional",text:"Defina a ação e o enquadramento.",sec:3,cost:8}])}><Plus/>Adicionar cena</button></div><Summary {...p}/></div>}
function Summary(p:any){return <div className="summary"><h3>Resumo da campanha</h3><dl>{[["Modelo",p.talent],["Formato",p.format],["Proporção",p.ratio],["Duração",p.duration],["Idioma","Português (Brasil)"]].map(x=><div key={x[0]}><dt>{x[0]}</dt><dd>{x[1]}</dd></div>)}</dl><div className="clean"><Check/><span><strong>Vídeo limpo</strong><small>Sem textos ou legendas</small></span></div><div className="total"><span>Custo estimado</span><strong>{p.total} <small>créditos</small></strong><p>Só debitamos após a geração ser concluída.</p></div></div>}
function History({start}:{start:()=>void}){return <section className="dashboard"><div className="hello"><div><span>BIBLIOTECA CRIATIVA</span><h1>Minhas campanhas</h1><p>Gerencie vídeos, rascunhos e variações.</p></div><button className="primary" onClick={start}><Plus/>Nova campanha</button></div><div className="filters"><label><Search/><input placeholder="Buscar campanha"/></label><button>Todos os status</button><button>Mais recentes</button></div><div className="grid four"><Campaign title="Glow Serum" meta="Vídeo UGC · 15s · Hoje" status="Concluído" color="peach"/><Campaign title="Urban Sneakers" meta="Lifestyle · 30s · Hoje" status="Processando 64%" color="blue"/><Campaign title="Café Origem" meta="Produto premium · Ontem" status="Rascunho" color="brown"/><Campaign title="Bolsa Aura" meta="Comercial · 15s · 28 ago" status="Concluído" color="purple"/></div></section>}
function Panel({children}:{children:React.ReactNode}){return <div className="panel">{children}</div>}function Intro({title,text,left}:{title:string;text:string;left?:boolean}){return <div className={"intro "+(left?"left":"")}><h2>{title}</h2><p>{text}</p></div>}function Choice({title,children}:{title:string;children:React.ReactNode}){return <div className="choice"><label>{title}</label>{children}</div>}
